x-template: &service-template
  restart: always
  deploy:
    mode: replicated
    replicas: 1
    update_config:
      parallelism: 1
      delay: 10s
      failure_action: rollback
    rollback_config:
      parallelism: 1
      delay: 30s
      failure_action: pause
      monitor: 60s
  volumes:
    - ${HOME}/Documents:${HOME}/Documents:z
    - ${HOME}/dotfiles:${HOME}/dotfiles:z
    - ${PWD}:${PWD}:z
    - dev_home:/home/${USER:-app}:z
    - ${HOME}/.oh-my-zsh:${HOME}/.oh-my-zsh:z
    - ${HOME}/.config:${HOME}/.config:z
    - ${HOME}/.ssh:${HOME}/.ssh:z
    - ${HOME}/.aws:${HOME}/.aws:z
    - ${HOME}/.gnupg:${HOME}/.gnupg:z
    - ${TMUX_SOCKET_DIR}:${TMUX_SOCKET_DIR}:z,

services:
  app:
    <<: *service-template
    image: mcmillanator/python
    build:
      args:
        IMAGE: mcmillanator/prebuilt-python

volumes:
  dev_home:
